export const data = [
    {
      title: "Meta Logo",
      company: "SpaceX Inc.",
      id: "88713620",
      date: "26th Jan 2020",
      status: "Live/Registered",
      registeredDate: "26 Jun 2020",
      renewalDate: "26 Dec 2027",
      classes: [45, 8, 8],
      description: "Computer services, Social Media, Networking, Virtual Communities, Community",
    },
    {
      title: "Meta Logo",
      company: "SpaceX Inc.",
      id: "88713621",
      date: "27th Jan 2020",
      status: "Live/Pending",
      registeredDate: "27 Jun 2020",
      renewalDate: "27 Dec 2027",
      classes: [45, 8, 8],
      description: "Computer services, Social Media, Networking, Virtual Communities, Community",
    },
    {
      title: "Meta Logo",
      company: "SpaceX Inc.",
      id: "88713622",
      date: "28th Jan 2020",
      status: "Dead/Abandoned",
      registeredDate: "28 Jun 2020",
      renewalDate: "28 Dec 2027",
      classes: [45, 8, 8],
      description: "Computer services, Social Media, Networking, Virtual Communities, Community",
    },
    {
      title: "Meta Logo",
      company: "SpaceX Inc.",
      id: "88713623",
      date: "29th Jan 2020",
      status: "Others",
      registeredDate: "29 Jun 2020",
      renewalDate: "29 Dec 2027",
      classes: [45, 8, 8],
      description: "Computer services, Social Media, Networking, Virtual Communities, Community",
    },
    {
      title: "Meta Logo",
      company: "FACEBOOK INC.",
      id: "88713624",
      date: "30th Jan 2020",
      status: "Live/Registered",
      registeredDate: "30 Jun 2020",
      renewalDate: "30 Dec 2027",
      classes: [45, 8, 8],
      description: "Computer services, Social Media, Networking, Virtual Communities, Community",
    },
    {
      title: "Meta Logo",
      company: "LEGALFORCE RAPC.",
      id: "88713625",
      date: "31st Jan 2020",
      status: "Live/Pending",
      registeredDate: "31 Jun 2020",
      renewalDate: "31 Dec 2027",
      classes: [45, 8, 8],
      description: "Computer services, Social Media, Networking, Virtual Communities, Community",
    },
    {
      title: "Meta Logo",
      company: "FACEBOOK INC.",
      id: "88713626",
      date: "1st Feb 2020",
      status: "Dead/Abandoned",
      registeredDate: "1 Jul 2020",
      renewalDate: "1 Jan 2028",
      classes: [45, 8, 8],
      description: "Computer services, Social Media, Networking, Virtual Communities, Community",
    },
    {
      title: "Meta Logo",
      company: "Tesla, Inc.",
      id: "88713627",
      date: "2nd Feb 2020",
      status: "Others",
      registeredDate: "2 Jul 2020",
      renewalDate: "2 Jan 2028",
      classes: [45, 8, 8],
      description: "Computer services, Social Media, Networking, Virtual Communities, Community",
    },
    {
      title: "Meta Logo",
      company: "FACEBOOK INC.",
      id: "88713628",
      date: "3rd Feb 2020",
      status: "Live/Registered",
      registeredDate: "3 Jul 2020",
      renewalDate: "3 Jan 2028",
      classes: [45, 8, 8],
      description: "Computer services, Social Media, Networking, Virtual Communities, Community",
    },
    {
      title: "Meta Logo",
      company: "Tesla, Inc.",
      id: "88713629",
      date: "4th Feb 2020",
      status: "Live/Pending",
      registeredDate: "4 Jul 2020",
      renewalDate: "4 Jan 2028",
      classes: [45, 8, 8],
      description: "Computer services, Social Media, Networking, Virtual Communities, Community",
    }
  ];

